"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getStore = exports.storeStrategy = exports.StoreStrategy = exports.getApiStore = exports.storePut = exports.storePost = exports.storePatch = exports.storeGet = exports.storeFetch = exports.storeDelete = exports.StoreApiService = exports.getMockStore = exports.MockService = exports.mockInterceptor = exports.resolveMockApi = exports.parseMockApi = exports.isStaticRequest = exports.isExistingApiRoute = exports.isApiRequest = exports.JsonService = exports.httpPut = exports.httpPost = exports.httpPatch = exports.httpGet = exports.httpFetch = exports.httpDelete = exports.pathJoin = exports.fsWriteJson = exports.fsWrite = exports.fsReadJson = exports.fsRead = exports.fsExists = exports.fsExistOrCreateFolder = exports.toFindParams = exports.apiPut = exports.apiPost = exports.apiPatch = exports.apiGet = exports.apiFetch = exports.apiDelete = exports.apiHandler = void 0;
var api_helper_1 = require("@core/api/api.helper");
Object.defineProperty(exports, "apiHandler", { enumerable: true, get: function () { return api_helper_1.apiHandler; } });
var api_service_1 = require("@core/api/api.service");
Object.defineProperty(exports, "apiDelete", { enumerable: true, get: function () { return api_service_1.apiDelete; } });
Object.defineProperty(exports, "apiFetch", { enumerable: true, get: function () { return api_service_1.apiFetch; } });
Object.defineProperty(exports, "apiGet", { enumerable: true, get: function () { return api_service_1.apiGet; } });
Object.defineProperty(exports, "apiPatch", { enumerable: true, get: function () { return api_service_1.apiPatch; } });
Object.defineProperty(exports, "apiPost", { enumerable: true, get: function () { return api_service_1.apiPost; } });
Object.defineProperty(exports, "apiPut", { enumerable: true, get: function () { return api_service_1.apiPut; } });
var entity_1 = require("@core/entity/entity");
Object.defineProperty(exports, "toFindParams", { enumerable: true, get: function () { return entity_1.toFindParams; } });
var fs_service_1 = require("@core/fs/fs.service");
Object.defineProperty(exports, "fsExistOrCreateFolder", { enumerable: true, get: function () { return fs_service_1.fsExistOrCreateFolder; } });
Object.defineProperty(exports, "fsExists", { enumerable: true, get: function () { return fs_service_1.fsExists; } });
Object.defineProperty(exports, "fsRead", { enumerable: true, get: function () { return fs_service_1.fsRead; } });
Object.defineProperty(exports, "fsReadJson", { enumerable: true, get: function () { return fs_service_1.fsReadJson; } });
Object.defineProperty(exports, "fsWrite", { enumerable: true, get: function () { return fs_service_1.fsWrite; } });
Object.defineProperty(exports, "fsWriteJson", { enumerable: true, get: function () { return fs_service_1.fsWriteJson; } });
Object.defineProperty(exports, "pathJoin", { enumerable: true, get: function () { return fs_service_1.pathJoin; } });
var http_service_1 = require("@core/http/http.service");
Object.defineProperty(exports, "httpDelete", { enumerable: true, get: function () { return http_service_1.httpDelete; } });
Object.defineProperty(exports, "httpFetch", { enumerable: true, get: function () { return http_service_1.httpFetch; } });
Object.defineProperty(exports, "httpGet", { enumerable: true, get: function () { return http_service_1.httpGet; } });
Object.defineProperty(exports, "httpPatch", { enumerable: true, get: function () { return http_service_1.httpPatch; } });
Object.defineProperty(exports, "httpPost", { enumerable: true, get: function () { return http_service_1.httpPost; } });
Object.defineProperty(exports, "httpPut", { enumerable: true, get: function () { return http_service_1.httpPut; } });
var json_service_1 = require("@core/json/json.service");
Object.defineProperty(exports, "JsonService", { enumerable: true, get: function () { return __importDefault(json_service_1).default; } });
var middleware_service_1 = require("@core/middleware/middleware.service");
Object.defineProperty(exports, "isApiRequest", { enumerable: true, get: function () { return middleware_service_1.isApiRequest; } });
Object.defineProperty(exports, "isExistingApiRoute", { enumerable: true, get: function () { return middleware_service_1.isExistingApiRoute; } });
Object.defineProperty(exports, "isStaticRequest", { enumerable: true, get: function () { return middleware_service_1.isStaticRequest; } });
var mock_api_1 = require("@core/mock/mock.api");
Object.defineProperty(exports, "parseMockApi", { enumerable: true, get: function () { return mock_api_1.parseMockApi; } });
Object.defineProperty(exports, "resolveMockApi", { enumerable: true, get: function () { return mock_api_1.resolveMockApi; } });
var mock_interceptor_1 = require("@core/mock/mock.interceptor");
Object.defineProperty(exports, "mockInterceptor", { enumerable: true, get: function () { return mock_interceptor_1.mockInterceptor; } });
var mock_service_1 = require("@core/mock/mock.service");
Object.defineProperty(exports, "MockService", { enumerable: true, get: function () { return __importDefault(mock_service_1).default; } });
var mock_store_1 = require("@core/mock/mock.store");
Object.defineProperty(exports, "getMockStore", { enumerable: true, get: function () { return mock_store_1.getMockStore; } });
var store_api_service_1 = require("@core/store-api/store-api.service");
Object.defineProperty(exports, "StoreApiService", { enumerable: true, get: function () { return __importDefault(store_api_service_1).default; } });
Object.defineProperty(exports, "storeDelete", { enumerable: true, get: function () { return store_api_service_1.storeDelete; } });
Object.defineProperty(exports, "storeFetch", { enumerable: true, get: function () { return store_api_service_1.storeFetch; } });
Object.defineProperty(exports, "storeGet", { enumerable: true, get: function () { return store_api_service_1.storeGet; } });
Object.defineProperty(exports, "storePatch", { enumerable: true, get: function () { return store_api_service_1.storePatch; } });
Object.defineProperty(exports, "storePost", { enumerable: true, get: function () { return store_api_service_1.storePost; } });
Object.defineProperty(exports, "storePut", { enumerable: true, get: function () { return store_api_service_1.storePut; } });
var store_api_store_1 = require("@core/store-api/store-api.store");
Object.defineProperty(exports, "getApiStore", { enumerable: true, get: function () { return store_api_store_1.getApiStore; } });
var store_1 = require("@core/store/store");
Object.defineProperty(exports, "StoreStrategy", { enumerable: true, get: function () { return store_1.StoreStrategy; } });
Object.defineProperty(exports, "storeStrategy", { enumerable: true, get: function () { return store_1.storeStrategy; } });
var store_service_1 = require("@core/store/store.service");
Object.defineProperty(exports, "getStore", { enumerable: true, get: function () { return store_service_1.getStore; } });
__exportStar(require("@core/utils"), exports);
